doodlum/skyrim-community-shaders

src/Features/DistantTreeLighting.cpp
src/Features/GrassCollision.cpp
src/Features/GrassLighting.cpp
src/Features/ScreenSpaceShadows.cpp

https://github.com/doodlum/skyrim-community-shaders/pull/10

simplify json io with nlohmann json macro

---

.gitignore
CMakeLists.txt
include/PCH.h

Also fixes gitignore and a compilation error for latest visual studio 2022.

Fix VR compilation

---

features/Light Limit Fix/Shaders/LightLimitFix/LightLimitFix.hlsli
package/Shaders/Lighting.hlsl
src/Features/LightLimitFix.cpp

fix: fix alpha test in VR

---

CMakeLists.txt
src/Menu.cpp
src/ShaderCache.cpp
src/State.cpp
src/State.h
src/Util.cpp
vcpkg.json

This can set Shader Compiler defines for advanced debugging.

feat: add Shader Defines advanced option

---

features/Light Limit Fix/Shaders/LightLimitFix/ClusterBuildingCS.hlsl
features/Light Limit Fix/Shaders/LightLimitFix/ClusterCullingCS.hlsl
features/Light Limit Fix/Shaders/LightLimitFix/Common.hlsli

This is basically what @doodlum posted in discord for VR but simply added #if defines for VR.

Fix LLF for right eye VR

---

src/Menu.cpp

Allows hot loading of particle lights config settings

feat: reload ParticleLight ini on Load Settings

---

src/Menu.cpp

- Reordered and expanded General to give easier access to the global CS shaders toggle.
- Made Feature Version information disabled color to allow for easier scanning of the Feature list.

chore: WIP polish main menu

---

CMakeLists.txt
src/Features/LightLimitFix.cpp
src/Menu.cpp
src/Menu.h
src/ShaderCache.cpp
src/ShaderCache.h
src/State.cpp
src/XSEPlugin.cpp
vcpkg.json

Reverts doodlum/skyrim-community-shaders#106

Revert "chore: sync with dev"

---

src/Feature.cpp
src/Features/DynamicCubemaps.cpp
src/Features/DynamicCubemaps.h
src/Menu.cpp
src/State.cpp
src/Util.cpp
src/Util.h

With cubemaps enabled.
Hidden VR settings are in the Dynamic Cubemaps menu. The list we enable may change in the future. The `Test Interval` settings will not work with these settings however as they are not actually distributed ini settings.
Thanks to flyingparticle for finding the hidden settings.

fix: fix VR wetness

---

src/Features/WetnessEffects.cpp

Typo Fix in Wetness Effects settings

---

src/Menu.cpp
src/Menu.h
src/ShaderCache.cpp
src/ShaderCache.h

Add ability to isolate individual bad shaders for debugging. https://github.com/doodlum/skyrim-community-shaders/wiki/Developers#debugging-individual-shaders

feat: add debug shader mode

---

CMakeLists.txt
cmake/XSEPlugin.cmake
include/PCH.h
vcpkg.json

Fixes:
Dynamic Cubemap CTD
Controlmap changes blocking input
Issues due to changes with BSGraphics::Renderer
Adds latest NG which now has an openvr submodule dependency

fix: fix AE1130

---

features/Dynamic Cubemaps/Shaders/DynamicCubemaps/UpdateCubemapCS.hlsl
features/Wetness Effects/Shaders/Features/WetnessEffects.ini
features/Wetness Effects/Shaders/WetnessEffects/WetnessEffects.hlsli
package/Shaders/Lighting.hlsl
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

- Skin+Hair wetness control
- Minimum wetness control to help vertical surfaces look wet
- More visible puddles
- Tweaked lerpFactor to help balance between reducing shimmer and ghosting
- Bumped version to 1.0.0

feat: skin wetness, min wetness, and other wetness updates

---

src/Features/LightLimitFix.cpp
src/Hooks.cpp

This includes changes to address fixed RE in NG

build: update commonlib

---

features/Grass Lighting/Shaders/RunGrass.hlsl
features/Tree LOD Lighting/Shaders/DistantTree.hlsl
package/Shaders/DistantTree.hlsl
package/Shaders/RunGrass.hlsl

Reverts doodlum/skyrim-community-shaders#166

Revert "refactor: move RunGrass and DistantTree out of individual features and into main packages"

---

features/Wetness Effects/Shaders/Features/WetnessEffects.ini
features/Wetness Effects/Shaders/WetnessEffects/WetnessEffects.hlsli
package/Shaders/Lighting.hlsl
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

* New wetness system - that keeps track of the acutal amount of rain that has fallen or evaporated, and bases wetness on that.
* Puddles have independent wetness - meaning that they take longer to form and take longer to dry up as well.
* Weather transition speed option - to scale how long things take to get wet / dry.
* Statistics section - added to Wetness Settings

feat: add wetness system based on water depth

---

src/Bindings.cpp
src/Features/TerrainBlending.cpp

VR isn't functional but also includes simplification for variable access

fix: fix VR ctd

---

BuildRelease.bat
CMakeLists.txt
README.md

Also updated the readme and the BuildRelease.bat to simplify using custom preset

build: added AIO_ZIP_TO_DIST cmake flag to build AIO zip for testing

---

features/Wetness Effects/Shaders/Features/WetnessEffects.ini
features/Wetness Effects/Shaders/WetnessEffects/WetnessEffects.hlsli
package/Shaders/Lighting.hlsl
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

**Fixes:**
* Wetness no longer affects eyes
* Inverted PuddleRadius to better align it with actual puddle size
* Puddles now have their own wetness slider
* Added missing tooltips for wetness settings

fix: Wetness fixes for settings and eyes

---

features/Wetness Effects/Shaders/WetnessEffects/WetnessEffects.hlsli
package/Shaders/Lighting.hlsl
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

- Created user settings for the hardcoded values being used to adjust GetWetnessSpecular.
- Clamped WeatherTransitionSpeed to protect against crazy values breaking things.

chore: Move hardcoded values to user settings

---

package/Shaders/Lighting.hlsl
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

- Fixed splashes not lining up between the eyes in VR
- Added safeguards against timescale 0 breaking weatherTransitionPercentage

fix: fix raindrop effects

---

src/ShaderTools/ShaderCompiler.cpp
src/Util.cpp

* feat: allow debug compilation for compute shaders
* refactor: use Util::Compile instead of custom compile

feat: allow debug compilation for compute shaders (#226)
