doodlum/skyrim-community-shaders

package/SKSE/Plugins/CommunityShaders.json
src/Menu.cpp
src/Menu.h
src/State.cpp

Added the option for users to change the menu toggle key. Via menu or config file. Key ids in the config file use the following format: [https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes]( https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) (as a uint not hex). The default key is still the END key
Added error logging for the config not parsing.
Fixed DiskCache and Async options not setting correcly.
Should hopefully stop people complaining about the lack of the END key on their keyboard

Added menu toggle key option. Fixed general settings loading correctly

---

src/Features/DistantTreeLighting.cpp
src/Features/GrassCollision.cpp
src/Features/GrassLighting.cpp
src/Features/ScreenSpaceShadows.cpp

Can compile, not tested in-game since this is done sneakily during worktime.
There is no manual boolean type conversion tho.
My vscode formatter does things differently...

simplify json io with nlohmann json macro

---

src/Feature.cpp
src/Feature.h
src/Features/Clustered.h
src/Features/DistantTreeLighting.cpp
src/Features/DistantTreeLighting.h
src/Features/GrassCollision.cpp
src/Features/GrassCollision.h
src/Features/GrassLighting.cpp
src/Features/GrassLighting.h
src/Features/ScreenSpaceShadows.cpp
src/Features/ScreenSpaceShadows.h
src/Menu.cpp
src/ShaderCache.cpp
src/State.cpp

Note:
- Compiled and tested this time;
- Duplicate version strings, `ValidateCache` and `WriteDiskCacheInfo` implementations are eliminated; `Load` is simplified;
- I refrained from using templates, otherwise singletons and settings I/O may be interfaced;
- `enabled` and `enabledFeature` are unified into `loaded`, as that is what the logger says. Except for `ScreenSpaceShadows`, It has both;
- Feature names. You may further combine `GetName` and `GetIniName` since they're the same in all cases. Even more agressive, deduce ini filenames from the name by eliminating space and hyphens.
- Totally public feature classes are structs now;
- All features are contained within a vector, obtained with `Feature::GetFeatureList()`. The list order implies function call orders.
- `Clustered` is …

abstract common feature class

---

features/Grass Lighting/Shaders/RunGrass.hlsl
src/Features/Clustered.cpp
src/Features/Clustered.h
src/Features/GrassLighting.cpp
src/Features/GrassLighting.h
src/ShaderCache.cpp

This is an initial attempt to combine flat and VR GrasShader code. However, the flat code does not appear to work and still needs to be fixed.
VR looks like it works. Flat DLL looks broken using the build. The combined `Rungrass.hlsl` appears to work fine in Flat using the Nexus version of the Flat DLL.

Add VR preprocessor def for GrassShader

---

features/Grass Lighting/Shaders/RunGrass.hlsl
package/Shaders/RunGrass.hlsl
src/Features/GrassLighting.cpp
src/Features/GrassLighting.h

Tested in VR and 1.5.97. 
Here's what fixed it:
- I inadvertently clobbered PerFrame later in the shader code so that's why the cb was broken. Renamed the conflict so the shader should work.
- There was also a random bug in grasslighting. I'm not sure why the helper function messed things up but undoing it seems to have resolved the lighting issue.
Lastly, I also undid your inadvertent update of `package/Shaders/RunGrass.hlsl`.

Fix VR and Flat grass lighting

---

features/Grass Lighting/Shaders/RunGrass.hlsl
src/Menu.cpp
src/ShaderCache.cpp
src/State.cpp
src/State.h
src/Util.cpp
src/Util.h

Please note the change to menu open status. We definitely needed it in VR since our res is much smaller, but you may want to revert that or cherry pick the other changes.

Various developer improvements for shader compilation

---

.github/workflows/build.yaml

This should help automate building test releases for both branches and the mainline. It takes a lot longer than building on a typical programmer PC with fast disks and warm caches, but it will generate reproducible builds and maybe reduce some of the by-hand work CS contributors are doing.
The workflow generates a mod structure identical to the one the bat files generates, then compresses the result into a 7zip archive. The archive is then uploaded as an asset to a draft GitHub release named for the tag. To publish the release on GitHub, a human must edit the release notes and press the publish button.
This workflow caches the cmake `build` directory. The vcpkg action caches the vcpkg binary artifacts. Most of the build time is currently spent rebuilding CommonLibSSE-NG because it's …

A workflow for building releases on tag push

---

features/Light Limit Fix/ParticleLights/black.ini
features/Light Limit Fix/ParticleLights/enblightglow.ini
features/Light Limit Fix/ParticleLights/fxglowenb.ini
features/Light Limit Fix/ParticleLights/glowsoft01_enbl.ini
src/Features/LightLimitFIx/ParticleLights.cpp
src/Features/LightLimitFIx/ParticleLights.h
src/Features/LightLimitFix.cpp
src/Features/LightLimitFix.h
src/XSEPlugin.cpp

This uses a config system with defaults, to control different basic settings about particle lights.
Typically, all that is needed is to control the culling parameter which should always be enabled on any particle light textures that are empty, but this method also avoids false positives such as on the player torch or candlelight spell, as well as scenarios, mainly with Rudy ENB Lights where the radius is much larger than the actual light to avoid frustum culling issues.
The flicker parameters are based on the game's own system, but implement completely differently.
The config loader class was separated due to how large LightLimitFix.cpp file is becoming, as well as it existing outside of rendering.

Initial particle lights config system

---

features/Grass Lighting/Shaders/RunGrass.hlsl
package/Shaders/Lighting.hlsl
src/Features/LightLimitFix.cpp

Testing indicates the WS position should be the same for the clustering algorithm. Instead of doing a pass, this just makes that assumption so both eyes have the same WS position for each light.

fix: always populate right eye WS for particles

---

COPYING
EXCEPTIONS.md
README.md

This will require approval or comment accepting this by all [contributors](https://github.com/doodlum/skyrim-community-shaders/graphs/contributors).
What this does is sets the license to [GPL-3.0-or-later](COPYING) WITH [Modding Exception AND GPL-3.0 Linking Exception (with Corresponding Source)](EXCEPTIONS.md).  In other words, this makes Community Shaders GPL which means anyone who distributes it must share their source code. This can be overridden by a specific license within the [Shaders ](https://github.com/alandtse/skyrim-community-shaders#shaders) directories.
@doodlum If you want something specific in [features ](https://github.com/doodlum/skyrim-community-shaders/tree/main/features)or [package/shaders](https://github.com/doodlum/skyrim-community-shaders/tree/main/package/Shaders), …

docs: set GPL license for project

---

.gitignore
Build Release.bat
CMakeLists.txt
CMakeUserPresets.json.template
src/Features/LightLimitFix.cpp

fixes #63
Added 2 options to CMake:
- AUTO_PLUGIN_DEPLOYMENT (default OFF), requires a ENV variable (CommunityShadersOutputDir)
This copies first package folder in root, then the DLL and PDB, then all addons (No orders on addons for now)
- ZIP_TO_DIST (default ON)
```
[cmake] Copying base CommunityShader into D:/dev/private/skyrim-community-shaders/build/zip.
[cmake] Zipping D:/dev/private/skyrim-community-shaders/build/zip to D:/dev/private/skyrim-community-shaders/dist/CommunityShaders.7z
[cmake] Zipping D:/dev/private/skyrim-community-shaders/features/Complex Parallax Materials to D:/dev/private/skyrim-community-shaders/dist/Complex Parallax Materials.7z
[cmake] Zipping D:/dev/private/skyrim-community-shaders/features/Grass Collision to …
```

build: added automatic plugin deployment

---

features/Grass Lighting/Shaders/RunGrass.hlsl
features/Light Limit Fix/Shaders/LightLimitFix/LightLimitFix.hlsli
package/Shaders/Lighting.hlsl
src/Features/LightLimitFix.cpp
src/State.cpp
src/State.h
src/XSEPlugin.cpp

User configs will be saved in `CommunityShadersUSER.json`. This will be loaded first and then fallback to `CommunityShaders.json`.
We should probably add logic that will invalidate a config if its version is too old using the `Version` key.
closes #66

feat: allow user specific configs

---

src/Features/DistantTreeLighting.cpp
src/Features/ExtendedMaterials.cpp
src/Features/GrassCollision.cpp
src/Features/GrassLighting.cpp
src/Features/LightLimitFix.cpp
src/Features/ScreenSpaceShadows.cpp
src/Features/WaterBlending.cpp

- All options now have tooltips added.
- Tooltip text in TextWrapped has been converted into tooltips.
- Some organizational updates to the different sections.

chore: polish Feature menus

---

README.md

Rework of Readme's instructions to help clarify installation and configuration of requirements to compile Community Shaders.

docs: improve compilation instructions

---

src/Features/ExtendedMaterials.cpp
src/Features/ExtendedMaterials.h
src/XSEPlugin.cpp

bLandSpecular may be disabled by certain mod lists and is necessary for
terrain parallax. This will force the setting to true when Terrain
Parallax is enabled.

fix: set bLandSpecular to support Terrain Parallax

---

.github/workflows/build.yaml

~~Added a workflow that build and creates a release on the fork repo, will run on every fork push. **Not on doodlom repo.**~~
Example release for this PR:
https://github.com/FlayaN/skyrim-community-shaders/releases/tag/untagged-59d9606a360720ff5014
* Uploads all the zip files (the output from CMAKE option `ZIP_TO_DIST`)
* ~~Creates a combined zip with all the files in one package (Same files that are copied to output when using `AUTO_PLUGIN_DEPLOYMENT`)~~
This allows to easier test a PR before approving it, can also make "alpha/beta" releases easier for posting them on discord in #forums

ci: update build workflow to include assets

---

src/Menu.cpp
src/ShaderCache.cpp
src/ShaderCache.h

Replacing Compiling Shaders text with a progress bar. Debug mode will provide the original text with failures/hits.

chore: use progress bar instead of text

---

src/XSEPlugin.cpp

Fixes regression from 0b49ae9. ShaderCache settings would always be default.
Removing redundant load settings exposed where we were setting default settings for ShaderCache. This is unnecessary due to default values and the fact we ship a config file that is fully populated.

fix: remove forced settings for shadercache

---

src/Features/DistantTreeLighting.cpp
src/Features/GrassLighting.cpp
src/Features/LightLimitFix.cpp
src/Features/SubsurfaceScattering.cpp
src/Util.h

Note, VR is not working anymore and has a red tint to everything. However, the fixes below are tested in flat/VR for SSS before the last commit.
I am seeing this in both flat and VR.

fix: fix subsurface-scattering for VR

---

src/Menu.cpp
src/Menu.h
src/ShaderCache.cpp
src/ShaderCache.h
src/State.cpp
src/XSEPlugin.cpp

Compiler threads may be changed in the `Advanced->Compiler Threads` menu. Defaults to the available cores - 1, but may be adjusted from 1 to maximum cores. Compiler threads also have been changed to `background` priority to prevent lock ups on start.

feat: allow adjustment of compiler threads

---

src/Menu.cpp
src/Menu.h
src/ShaderCache.cpp
src/ShaderCache.h
src/State.cpp
src/XSEPlugin.cpp

This reverts commit 07d50a4c2412d380de00f52497cef5298c518c45.

revert: "feat: allow adjustment of compiler threads (#99)"

---

CMakeLists.txt
src/Menu.cpp
src/Menu.h
src/ShaderCache.cpp
src/ShaderCache.h
src/State.cpp
src/XSEPlugin.cpp
vcpkg.json

Compiler threads may be changed in the `Advanced->Compiler Threads`
menu. Defaults to the available cores - 1, but may be adjusted from 1 to
maximum cores. Compiler threads also have been changed to `background`
priority to prevent lock ups on start.
Switch to BS:thread_pool to abstract thread management and avoid
overhead of killing and starting threads. Instead, only add jobs to
pool when the number of active and queued threads is less than the
limit. The reason it's total and not just active is to avoid the case
where all tasks are dumped into the thread pool since the thread pool is
at the hardware maximum.
During compilation, one manager job is spawned to handle task
allocation and the remaining threads do the compilation work.
Users can now skip shader compilation before it is …

feat: improve compilation options

---

src/Feature.h
src/Features/ExtendedMaterials.h
src/Features/LightLimitFix.cpp
src/Features/LightLimitFix.h
src/Features/ScreenSpaceShadows.cpp
src/Features/ScreenSpaceShadows.h
src/Menu.cpp
src/State.cpp
src/State.h
src/XSEPlugin.cpp

Simplify feature loading by adding optional virtual functions in Feature.h that can be overriden by features. This will reduce the need to modify State.cpp, XSEPlugin.cpp & Menu.cpp when adding new features etc
Added to `Feature.h`:
- `DataLoaded` <-- Called by SKSE `kDataLoaded` event
- `PostPostLoad` <-- Called by SKSE `kPostPostLoad` event
- `ClearShaderCache` <-- Called by imgui clear shader cache button
- `DrawDeferred` <-- This one is not called yet, that is in the subsurface-scattering branch
Fixed almost all tasks of #97
Link to build for this PR -> https://github.com/FlayaN/skyrim-community-shaders/releases/tag/untagged-626eeecf0c4665d55ff6
Created this as a draft due to this should maybe wait until subsurface-scattering is in dev (Or maybe remove the DrawDeferred part of the …

feat: simplify feature loading

---

src/Feature.h
src/Features/ExtendedMaterials.cpp
src/Features/ExtendedMaterials.h
src/Features/GrassCollision.cpp
src/Features/GrassCollision.h
src/Features/LightLimitFix.cpp
src/Features/LightLimitFix.h
src/Features/RainWetnessEffects.cpp
src/Features/RainWetnessEffects.h
src/Features/ScreenSpaceShadows.cpp
src/Features/ScreenSpaceShadows.h
src/Features/WaterBlending.cpp
src/Features/WaterBlending.h
src/Menu.cpp
src/ShaderCache.cpp

Added virtual `GetShaderDefineName` to feature.h that can be overriden by each feature to specify the Shader define name for each feature.
Added virtual `HasShaderDefine` to feature.h to specify if `RE::BSShader::Type` is implemented by that feature, this is used in ShaderCache.cpp to know if it should add a define for each loaded feature
This PR will not require updating ShaderCache.cpp for each new/updated feature, can instead be fully controlled by the feature instead
Has tested basic functionality for each feature
Can download a release for this PR here https://github.com/FlayaN/skyrim-community-shaders/releases/tag/untagged-db023c4d6153eaa50ba7

refactor: move opt in for shaders to virtual feature function

---

src/Menu.cpp

This fixes #87 
Following the discussion in #87 , in `Menu.cpp` I've changed the multiline handling in **tooltips that use multiple text fields** (consecutive uses of `ImGui::Text()`).
According to the above, I identified and modified the tooltips for the below features:
- `Clear Shader Cache` button
- `Clear Disk Cache` button
- `Test Interval` slider
---
In the modified tooltips, I also maintained the habit of adding an **extra space at the end of the final string**, which was **already present** in the `Toggle Error Message` button tooltip:
https://github.com/doodlum/skyrim-community-shaders/blob/b105489c7fec25838b53b272b1446289f9fafe5b/src/Menu.cpp#L361-L365 ...and the `Compiler Threads` slider tooltip: https://github.com/doodlum/skyrim-community-shaders/blob/b105489c7fec25838b53b272b1 …

chore: break apart menu multiline strings

---

features/Grass Lighting/Shaders/RunGrass.hlsl

Potential fix for #124.
VR grass cull distance was calculated per eye, resulting in different cull distances for each eye.
This meant, that grass might be visible in the left eye, while culled in the right eye.
This is a potential fix, calculating the cull distance based on the first eye.

fix: fix inconsistent VR grass culling

---

package/Shaders/Lighting.hlsl

Triplanar mapping for projected diffuse textures (introduced by Better Dynamic Snow / Simplicity Of Snow / Shaders Of Solstheim).
Fixes texture striping when projection is parallel to object geometry, most notably for snow on Windhelm architecture.
Uses screen space derivatives because geometry normals don't help. Uses UV based triplanar mapping for performance.
Works for VR and flat screen, although it needs to hook into different code paths for each platform. The function "ComputeTriplanarUV" does the math.

Triplanar Mapping for Projected Textures

---

package/SKSE/Plugins/CommunityShaders.json
src/Menu.cpp
src/Menu.h

Adding a global effect hotkey

---

src/Features/DistantTreeLighting.cpp
src/Features/ExtendedMaterials.cpp
src/Features/GrassLighting.cpp
src/Features/LightLimitFix.cpp

Summary of Changes
---
Following our discussion in https://github.com/doodlum/skyrim-community-shaders/pull/119#issuecomment-1752174502, I searched for and handled consecutive `ImGui::Text()` calls in the feature code 
(in the **src** folder).
I used [git grep](https://git-scm.com/docs/git-grep) to find module files that have `ImGui::Text()` calls and consolidated tooltips that use consecutive `ImGui::Text()` calls.
I modified tooltips in the following modules:
- `DistantTreeLighting`:
* Complex Tree LOD Tooltip
* Subsurface Scattering tooltip
- `ExtendedMaterials`:
* Complex Material Checkbox tooltip
* Enable Parallax tooltip
* High Quality checkbox tooltip
* Blend Range slider tooltip
* Enable Shadows checkbox tooltip
- `GrassLighting`:
* Subsurface Scattering (SSS) Amount slider …

refactor: Consolidate multiline strings in feature code

---

src/State.cpp
src/State.h
src/XSEPlugin.cpp

Moves detection to postpostload so upscaler will
have loaded. SKSE loads in alphabetical order so
Community Shaders was loading first.

fix: fix detection of Skyrim Upscaler dll

---

features/Grass Lighting/Shaders/Features/GrassLighting.ini
features/Grass Lighting/Shaders/RunGrass.hlsl
src/Features/GrassLighting.cpp
src/Features/GrassLighting.h

Override the settings set by the grass mesh author. Complex grass authors can define the brightness for their grass meshes. However, some authors may not account for the extra lights available from Community Shaders. This option will treat their grass settings like non-complex grass. This was the default in Community Shaders < 0.7.0.

feat: allow override for complex grass lighting

---

features/Light Limit Fix/Shaders/LightLimitFix/LightLimitFix.hlsli
package/Shaders/Effect.hlsl
package/Shaders/Lighting.hlsl
package/Shaders/Water.hlsl
src/Features/LightLimitFix.cpp
src/Features/LightLimitFix.h
src/ShaderCache.cpp
src/ShaderCache.h

- Effect shaders should work 1:1 compared to vanilla
- Water shaders should work differently, since they have access to high quality normal maps. I found that vanilla water specularity is way too bright, so I've darkened it to match the new lighting on non-strict portal lights. Might improve performance vs vanilla because it reduces draw calls on water.
- VR is detected so that these flatrim-specific changes should not affect it.
- Some shadercache code has been refactored to be accessible elsewhere.

feat: add LLF support to effect and waters shaders

---

package/Shaders/Lighting.hlsl

The FirstPerson calculation was expecting FrameParams.y to return 0.0 if rendering first person body, 1.0 otherwise. 
VR is always first person but does not return 0.0.
Fix sets FirstPerson to 0.0 in VR.

fix: VR fix of the FirstPerson calculation for the Fog in Lighting Shader Reflections feature.

---

src/Hooks.cpp
src/Menu.cpp

* Allow inputs from gamepads and VR controllers when the CS Menu is open
* Returned CS Menu text color to white when all shader errors are fixed

fix: Some QoL Menu fixes

---

include/PCH.h
src/Hooks.cpp
src/Menu.cpp

Implemented wndproc hook to catch WM_KILLFOCUS and call 
```
Menu::GetSingleton()->OnFocusLost();
auto& io = ImGui::GetIO();
io.ClearInputKeys();
io.ClearEventsQueue();
```
Got some added info from "FiveLimbedCat/ProfJack" on discord, that we should also clear the io inputkeys
Got the addresses and offsets from Open Animation Replacer. Had to convert it to use the thunk/func version instead though!
Tested this on skyrim 1.6.1170.0
Now it will clear all ImGui input states when alt-tabbing
Link to diskussion on discord here:
https://discord.com/channels/1080142797870485606/1082470343119216751/1201664684261130250

fix: clear imgui inputs when window focus lost (alt-tabbing)

---

features/Dynamic Cubemaps/Shaders/DynamicCubemaps/DynamicCubemaps.hlsli
features/Grass Lighting/Shaders/RunGrass.hlsl
package/Shaders/Water.hlsl

Fixes bugged flickering black squares on water surfaces and probably other cubemap issues as well.

fix: black reflections on water for amd

---

features/Wetness Effects/Shaders/WetnessEffects/WetnessEffects.hlsli

Clamping the values of specularIrradiance fixes the black wet surfaces on AMD cards.

fix: wetness specular for amd

---

src/Menu.cpp

Setting the default text color to white.

chore: set default menu text color to white

---

src/Feature.h
src/Features/DistantTreeLighting.cpp
src/Features/DistantTreeLighting.h
src/Features/DynamicCubemaps.cpp
src/Features/DynamicCubemaps.h
src/Features/ExtendedMaterials.cpp
src/Features/ExtendedMaterials.h
src/Features/GrassCollision.cpp
src/Features/GrassCollision.h
src/Features/GrassLighting.cpp
src/Features/GrassLighting.h
src/Features/LightLimitFix.cpp
src/Features/LightLimitFix.h
src/Features/ScreenSpaceShadows.cpp
src/Features/ScreenSpaceShadows.h
src/Features/WaterBlending.cpp
src/Features/WaterBlending.h
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

Added option to restore defaults at the feature level for all features except dynamic cubemaps.
* Implemented virtual function on the Feature base class and then implemented it on all of the features. 
* Added a button to all feature settings menus to restore defaults - except for dynamic cubemaps
* Tested with a debugger attached to make sure that ImGui behaved

feat: add feature-level restore defaults option

---

src/Features/DistantTreeLighting.cpp
src/Features/DynamicCubemaps.cpp
src/Features/ExtendedMaterials.cpp
src/Features/GrassCollision.cpp
src/Features/GrassLighting.cpp
src/Features/LightLimitFix.cpp
src/Features/ScreenSpaceShadows.cpp
src/Features/WaterBlending.cpp
src/Features/WetnessEffects.cpp
src/Menu.cpp
src/Util.cpp
src/Util.h

Fixes https://github.com/doodlum/skyrim-community-shaders/issues/163
New tooltip usage:
```cpp
ImGui::SomeWidget();
if (auto _tt = Util::HoverTooltipWrapper()){
ImGui::Text("What the tooltip says.");
}
```

refactor: extract common UI codes, including restore default button, and hovered tooltip formatting

---

CMakeLists.txt
cmake/FeatureVersions.h.in
src/Feature.cpp
src/Feature.h
src/Menu.cpp

fix #145
This is how the cmake generated header file will look like:
I tested this by going into the manually editing some versions in skyrim data folder after compiling and changed some versions around. It will set loaded to false for the feature, add a log and show this in the UI:

feat: add feature version detection

---

src/Buffer.h
src/Util.cpp
src/Util.h

A few edits I made on my own demo branches.
- `StructuredBufferDesc` like `ConstantBufferDesc` for generic feature setting buffers (partially https://github.com/doodlum/skyrim-community-shaders/issues/185)
- `Texture1D` class
- `Texture2D` initialiser that takes an existing resource loaded by DirectXTex
- `FrameChecker` helper class for checking new frames when `Reset()` is not enough
- `floatx` vectors are now json-ifiable as fixed length arrays

chore: add helper functions and classes

---

.gitignore
features/Screen-Space Shadows/Shaders/Features/ScreenSpaceShadows.ini
features/Screen-Space Shadows/Shaders/ScreenSpaceShadows/Common.hlsl
features/Screen-Space Shadows/Shaders/ScreenSpaceShadows/FilterCS.hlsl
features/Screen-Space Shadows/Shaders/ScreenSpaceShadows/RaymarchCS.hlsl
features/Screen-Space Shadows/Shaders/ScreenSpaceShadows/ShadowsPS.hlsli
features/Tree LOD Lighting/Shaders/DistantTree.hlsl
package/Shaders/Lighting.hlsl
src/Feature.cpp
src/Features/ScreenSpaceShadows.cpp
src/Features/ScreenSpaceShadows.h

Created with @Andersw88 with some reference from @alandtse with this PR https://github.com/doodlum/skyrim-community-shaders/pull/36
Known issues / TODO:

feat: add vr support to screen space shadows

---

src/Menu.cpp
src/Menu.h

* ADDRESS_NODE: Allows outputting common addresses to clipboard for RE
* BUFFER_VIEWER_NODE: Allows output of buffer data to IMGUI

feat: add helper macros for IMGUI menus

---

CMakeLists.txt
src/ShaderCache.cpp
src/ShaderCache.h
src/XSEPlugin.cpp
vcpkg.json

Adds feature where changes to the shader .hlsl files will automatically recompile shaders.
Changes to RE::BSShader::Type files in Data\Shaders (e.g., Lighting.hlsl) will result in a type specific recompile. All other modification to hlsl/hlsli files will recompile all files since there isn't a way to detect what may be impacted.
closes #205

feat: recompile automatically for changed shaders

---

src/ShaderCache.cpp

Root cause was attempt to access deleted file's
timestamp.

fix: ctd when files were deleted from shaders path

---

features/Wetness Effects/Shaders/WetnessEffects/WetnessEffects.hlsli
src/Features/WetnessEffects.cpp
src/Features/WetnessEffects.h

- Added a user setting to allow raindrop splashes and ripples to occur at different speeds and set splashes to occur 10x slower than ripples by default.
- Adjusted the default setting for Skin Wetness to make it more visible

chore: separate raindrop splash and ripple intervals
